version: '2'
volumes:
  mysql:
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: pw
    ports:
      - "3333:3306"
  app:
    depends_on:
      - db
    build: ./
    image: php-with-pdo-mysql-xss:7.0.12-apache
    links:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      MYSQL_DSN: mysql:host=db;dbname=dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: pw
    volumes:
      - ./:/var/www/
